version: 2.1

jobs: # a basic unit of work in a run
  test: # your job name
    macos:
      xcode: 12.2.0 # version of Xcode
    steps:
      - checkout  # pull down code from
      - run:
          name: Run Unit Tests
          command: swift test --enable-code-coverage
#          command: |-
#              brew tap homebrew/cask-versions
#              brew update
#              brew tap homebrew/cask
#              brew install java
#              swift test --enable-code-coverage
#              xcrun llvm-cov show .build/debug/w3w-swift-wrapperPackageTests.xctest/Contents/MacOS/w3w-swift-wrapperPackageTests -instr-profile .build/debug/codecov/default.profdata > .build/cov.txt
#      - sonarcloud/scan
#orbs:
#  sonarcloud: sonarsource/sonarcloud@1.0.1
   
workflows:
  version: 2
  test_build:
    jobs: test
#      - test:
#          context: SonarCloud
