version: 2.1

jobs: # a basic unit of work in a run
  test: # your job name
    macos:
      xcode: 12.2.0 # version of Xcode
    steps:
      - checkout  # pull down code from
      - run:
          name: Run Unit Tests
          command: swift test
          
workflows:
  version: 2
  test_build:
    jobs:
      - test
