version: 2.1

jobs: # the jobs
  test: # your job name
    macos:
      xcode: 12.2.0 # version of Xcode
    steps:
      - checkout  # pull down code from
      - run:
          name: Run Unit Tests
          command: |-
              brew install sonar-scanner
              swift test --enable-code-coverage
              xcrun llvm-cov show .build/debug/w3w-swift-wrapperPackageTests.xctest/Contents/MacOS/w3w-swift-wrapperPackageTests -instr-profile .build/debug/codecov/default.profdata > .build/cov.txt
              sonar-scanner -Dsonar.projectKey=what3words_w3w-swift-wrapper -Dsonar.organization=what3words -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN -Dsonar.sources=Sources -Dsonar.exclusions=Sources/Lib/Bridges/SdkToApiBridge.swift -Dsonar.swift.coverage.reportPath=.build/cov.txt
   
workflows:
  version: 2
  test_build:
    jobs:
      - test
