version: 2.1

jobs: # a basic unit of work in a run
  test: # your job name
    macos:
      xcode: 12.2.0 # version of Xcode
    steps:
      - checkout  # pull down code from
      - run:
          name: Run Unit Tests
          command: swift test
      - coverage:
          name: Code Coverage
          command: xcrun llvm-cov show .build/debug/w3w-swift-wrapperPackageTests.xctest/Contents/MacOS/w3w-swift-wrapperPackageTests -instr-profile .build/debug/codecov/default.profdata > .build/cov.txt
          
workflows:
  version: 2
  test_build:
    jobs:
      - test
